[project]
name = 'Blockchain-Based-Fishing-Quota-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.catch-reporting]
path = 'contracts/catch-reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.quota-allocation]
path = 'contracts/quota-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.quota-trading]
path = 'contracts/quota-trading.clar'
clarity_version = 2
epoch = 2.5

[contracts.sustainability-monitoring]
path = 'contracts/sustainability-monitoring.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
